### ISSUE TITLE
Fields on some but not all subclasses

### ISSUE THREAD

**Issue by andybak** [craigds/django-typed-models#19] opened 2014-06-21 09:44 UTC
I was hoping this was possible:

```
class Animal(TypedModel):
    name = models.CharField(max_length=100)

class Cat(Animal):
    meow_volume = models.IntegerField()
    owner_name = models.CharField(max_length=100)

class Dog(Animal):
    bark_volume = models.IntegerField()
    owner_name = models.CharField(max_length=100)

class Bear(Animal):
    growl_volume = models.IntegerField()
```

But I get:

```
django.db.utils.ProgrammingError: column "owner_name" specified more than once
```

I know I could move 'owner_name' on to the base class but then Bears have an owner - which they shouldn't have.

Is there any way that the duplicate fields could be magically recognised and de-dupped? Obviously they would have to be identical - that would be a reasonable constraint to impose on this kind of arrangement.

**Comment by saltysealion** [comment] 2018-02-26 23:54
Any news on this? I am having the same issue.

**Comment by craigds** [comment] 2018-02-27 04:08
I think I probably missed this at the time. It actually looks like a dupe of #8, so I'll close this and update there

**Closed by craigds** 2018-02-27 04:08 UTC
