### ISSUE TITLE
Make _typedmodels_registry public

### ISSUE THREAD

**Issue by guettli** [craigds/django-typed-models#24] opened 2014-07-15 09:09 UTC
If you want to render a ChoiceField with all available subclasses of a TypedModel, you need `_typedmodels_registry`.

I think it should be part of the public API: I think the leading underscore should be removed.

**Comment by craigds** [comment] 2016-01-08 00:28
This is exposed by `get_type_classes()` so I'm going to close this as a dupe of #23

**Closed by craigds** 2016-01-08 00:28 UTC
